AWS_REGION=ap-southeast-2
AWS_PROFILE=monty
AWS_STAGING_BUCKET=montague-aws-staging
AWS_WEBSITE_BUCKET=montague-aws-website
AWS_CHUM_BUCKET=474457287269-chum-bucket
AWS_STACK_NAME_BASE=monty-base
AWS_STACK_NAME_BACKEND=monty-backend